/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import viewModel.MainMenuViewModel;
import model.User;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author 2100195
 */
public class MainMenuView extends javax.swing.JPanel {

    final private MyGame game;
    final private MainMenuViewModel viewModel;
    
    /**
     * Creates new form MainMenuView
     */
    public MainMenuView(MyGame daGame) {
        game = daGame;
        viewModel = new MainMenuViewModel();
        initComponents();
        setupTable();
    }
    
    /// mengisi tabel dengan data2
    private void setupTable(){
        /// mengambil data terbaru
        viewModel.fetchUserData();
        ArrayList<User> users = viewModel.getData();
        
        /// pengisian nama kolom dan nilai-nilai-nya
        String[] colNames = {"No.", "Name", "Scores", "Standings"};
        Object[][] data = null;
        if(users != null){
            data = new Object[users.size()][colNames.length];
            for(int i = 0; i < users.size(); i++){
                User user = users.get(i);
                data[i][0] = i + 1;
                data[i][1] = user.getName();
                data[i][2] = user.getScore();
                data[i][3] = user.getLandings();
            }
        }
        TableModel m = new DefaultTableModel(data, colNames);
        mainTable.setModel(m);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playBBtn = new javax.swing.JButton();
        titleLbl = new javax.swing.JLabel();
        quitBtn = new javax.swing.JButton();
        usernameField = new javax.swing.JTextField();
        usernameLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mainTable = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(600, 800));

        playBBtn.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        playBBtn.setText("Play");
        playBBtn.setMaximumSize(new java.awt.Dimension(60, 120));
        playBBtn.setMinimumSize(new java.awt.Dimension(60, 120));
        playBBtn.setPreferredSize(new java.awt.Dimension(60, 120));
        playBBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playBBtnActionPerformed(evt);
            }
        });

        titleLbl.setFont(new java.awt.Font("sansserif", 0, 48)); // NOI18N
        titleLbl.setText("KEEP STANDING");

        quitBtn.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        quitBtn.setText("Quit");
        quitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitBtnActionPerformed(evt);
            }
        });

        usernameField.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N

        usernameLbl.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        usernameLbl.setText("Username :");

        mainTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(mainTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(titleLbl)
                .addGap(190, 190, 190))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(usernameLbl)
                                .addGap(35, 35, 35)
                                .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(playBBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(125, 125, 125)
                        .addComponent(quitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(177, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLbl)
                    .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(playBBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void playBBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playBBtnActionPerformed
        String name = usernameField.getText();
        
        if(name != null){
            
            /// bila nama tidak ada di db, anggap membuat
            /// player baru
            if(viewModel.getDataByName(name) == null){
                viewModel.insertUser(name);
                setupTable();
            }
            
            /// masuk ke "game" dengan nama 
            /// player yang dimasukkan
            game.switchToGameView(name);
        }
    }//GEN-LAST:event_playBBtnActionPerformed

    private void quitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitBtnActionPerformed
        this.game.stop();
    }//GEN-LAST:event_quitBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable mainTable;
    private javax.swing.JButton playBBtn;
    private javax.swing.JButton quitBtn;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameLbl;
    // End of variables declaration//GEN-END:variables
}
